### ISSUE TITLE
村紹介のページを追加

### ISSUE THREAD

**Issue by Hayate09273** [HimaJyun/amit.jyn.jp#19]
非公式Discordで、追加しないかという話が出ていますのでここに投稿しておきます。
↓適当に作ってみました。
https://github.com/Hayate09273/amit.jyn.jp/blob/village/content/village/index.md

**Comment by HimaJyun** [comment]
とても良いアイデアだと思います 👍 
村一覧ページもデザインがTT一覧ページと近い感じになっていてわかりやすいと思います。


良いアイデアではあるのですが、いくつか課題があります。

僕も村ページ追加は何度か考えたんですが、なによりも大きな障害になっているのは編集者不足です。
見ての通り、GitHubを使う今の編集スタイルは難易度がめちゃくちゃ高くて編集したくても出来ない人も多いと思います。

編集者が少ないので、村がどこにどれだけあるか把握しきれないとか、村の変化に編集が付いていけない可能性が高いです。

それと、TTと違って村には管理者が必要です。
村固有のルールとかもあるので、TTみたいに編集者側で「ここにあるな、追加しとこ」みたいな事ができません。(個別にルールとか聞いて回って都度編集するのは……めっちゃ大変です)

そんなこんなで、どうしたら良いかなぁ……と考えています。どうしたら良いと思いますか？

BBSかどこかで掲載希望の人たちにスクショとかルールを書き込んでもらって、それを編集者が反映していく……とか？
昔あったBuyBuyRegion(現在破損中)を修理/復活させて土地のレンタルを可能にして、ルールは入り口に立て看板、Webには座標と写真をメインに記載……とかは人手が少なくて済みそうですよね。
僕は鶏を割くのに牛刀を使っちゃうタイプなので、WebのWiki化なんてのも検討してたりはします。

何か良い案があれば教えてください。

**Comment by Hayate09273** [comment]
返信ありがとうございます。

> BBSかどこかで掲載希望の人たちにスクショとかルールを書き込んでもらって、それを編集者が反映していく……とか？
この方法で行ける気がしてます。もう一つ気になるのは、TTと同じように1ページに全て書くか、1つの村につき1ページ作るかという点です。（NAKASHIさんがチラっと言ってた）
希望者が3人いれば多い方だと思うので、僕は前者で大丈夫だと思います。
NAKASHIさんの考えも聞きたいですね。 @NAKASHI0131

**Comment by NAKASHI0131** [comment]
- 編集者不足について
このままgitでの管理であればBBS、botを利用したディスコ等で簡単に編集リクエスト(githubにAPI投げればissueをオープンできるらしいし)できればまだ楽なんですが、、、
wiki化であれば簡単に誰でも編集リクエスト送れるのはいいですね。
(今の超高速なHPとおさらばなのはちょっとさみしい)
ただ、githubみたいにいつ誰がどこを編集したのを見れるような物がいいですね。

- 掲載基準について
僕もBBSでの募集でいいと思います。
実際その方がみんなもやりやすいだろうし。
BuyBuyRegionでの土地のレンタルをできるようになった場合、プレイヤーが長時間ログインして無くて土地を開けたい場合、土地の設定はいじれても家の中にあるチェスト類の保護がいじれないのでそこがちょっと気になりますね。(コミュニケーションをしなくても借りれるので今まで以上に多発する可能性)

- ページ分割について
一ページに10個とか載せてページが無駄に長くなるのもちょっとなって思ったのですが、目次機能もあるのでこれはスルーでもいいのかなって思います。

**Comment by HimaJyun** [comment]
僕は将来的にはWiki化したいなと考えているのですが、まぁそれはそれ……当面の間はBBSで要望してもらうスタイルにしましょうか。
(ちなみに、僕も編集履歴はあった方が良いと考えているので、Wikiはそれに対応したものを選びます)

ページは1つにまとめたので良いと思います。
目次ありますし、仮に目次がなかったとしてもみんな読みたいところまでダーっとスクロールしてると思います。

BuyBuyRegionなのですが、仮にレンタル機能を付けるとしたら残存チェストの対策の強化もすると思います。
ChestSafeには[範囲検索API](https://github.com/HimaJyun/ChestSafe/blob/master/src/main/java/jp/jyn/chestsafe/protection/ProtectionRepository.java#L297)と[所有者操作API](https://github.com/HimaJyun/ChestSafe/blob/master/src/main/java/jp/jyn/chestsafe/protection/Protection.java#L61)があるので、貸し出しに合わせて範囲内のチェストを一括で操作する事は可能です。

---

ここで「よし、じゃあBBSで運用しよう」と決めてもそれを知られなければ意味がないです。
なので、「ここに掲載できますよ」の意思表示のために村ページを作ろうと思います。

村で掲載するべき情報はこんな感じ？
- スクショ
- 座標
- 村長
- アクセス(TTページもそうなんですが、「EbiFlyでn分」は要らないと思います。時間の計測が面倒な割にほぼ全域が30秒～2分の範囲内に収まってしまうので)
- ルール
- 村長メッセージ

他に何か必要そうな情報があれば教えてください。

**Comment by NAKASHI0131** [comment]
`ChestSafeには範囲検索APIと所有者操作APIがある` でしたら、かなり楽に運営できますね（マンションの経営もできそう）

掲する情報は

> スクショ
    座標
    村長
    アクセス
    ルール
    村長メッセージ

に加え`コンセプト or 村のイメージ`を載せた方がいいと思います。
和風や洋風などの記載があればそのイメージに沿って建築がしやすいと思うので。

flyでの移動時間はいらないかもですね。一回住んでしまえばhomeでいつでも飛べますし。

**Comment by Hayate09273** [comment]
その7つで大丈夫だと思います。
マンション作ろうかな～なんて思ってる（思ってるだけ）ので、BuyBuyRegionが復活したら便利そうですね！

**Comment by HimaJyun** [comment]
現時点だと「村」と表現していますが、これだとマイクラの村(ﾌｩｳｳﾝの奴が居る方)と紛らわしいので今後は「町(town)」に表現を統一していこうと思います。(個々の町の名前として「○○村」と付けるのは無問題、あくまでWeb上の表現の話)

「町(town)」と「街(city)」のどちらにするか迷ったのですが、街だと大規模なイメージがあるので「村」からの置き換えとしては「町」の方が適していると考えました
