### ISSUE TITLE
dynmapマーカ追加方法の記述

### ISSUE THREAD

**Issue by NAKASHI0131** [HimaJyun/amit.jyn.jp#23]
TTの場所を表すdynmapマーカ追加方法の記述を[コマンドページ](https://amit.jyn.jp/command/)に追加
[ルール](https://amit.jyn.jp/rule/)には該当のリンクと説明を貼る

TTだけではなく鉄道駅のマーカもあれば便利だと思います。
鉄道駅のマーカーが不要と判断された場合、HPから鉄道でのアクセスに関する文章を削除

**Comment by HimaJyun** [comment]
鉄道、TT、村の3つがあればそこそこ便利そうですよね。
ただ/dmarker系は数が多いので、ある程度数を絞った方がよさそうです。(参考: [e-craft.ioに書いてる奴](https://e-craft.io/bukkit/plugin/dynmap/))

**Comment by NAKASHI0131** [comment]
基本的に/dmarkerは他の人が設置したマーカーもいじれるみたいなので(delete系はモデレーター以上が安全、、？)、やり込み以上の権限を持った人専用にするか、専用の権限を指名したプレイヤー(鉄道制作者)に渡す感じですかね。
それか、dynmap.marker.signを解放して、簡単に作れるようにするか（よくわかってない）

> /dmarker add
/dmarker movehere
/dmarker update (アイコン、ラベル)
/dmarker delete 
/dmarker list
/dmarker icons
/dmarker addcorner
/dmarker clearcorners
/dmarker updateline
/dmarker deleteline
/dmarker listlines

最低限と思ったんですが、それでも多いですね、、、

村のマーカー設置についてはHPに搭載している物のみに制限した方がいいかもですね（マーカーだけあって説明がないと混乱するため）

路線名、駅名は少し整理した方が良さそうです。駅固有の英数字([駅ナンバリング](https://ja.wikipedia.org/wiki/%E9%A7%85%E3%83%8A%E3%83%B3%E3%83%90%E3%83%AA%E3%83%B3%E3%82%B0))をつけると少しは乗り換えしやすいのかなと。

**Comment by HimaJyun** [comment]
`dynmap.marker.sign`を解放する方がよさそうですね。
コマンドだと割と間違える人居そうですし、権限調整もページ編集も面倒です。(Dynmapから見てると明らかに操作を間違えてるっぽいめっちゃ狭い保護、よくありますよね)

とりあえずTTと村でやってみましょう、良い感じっぽければ順次対象を広げていく。
村のWeb掲載時にDynmapへのマーカー登録も義務付ければ「機能は解放してるのに全く使われてない」という事も起きないはず。
(線路は色々とぐちゃぐちゃなので、少し後回し)

ちなみにですが、追加するset(レイヤー)はデフォルト表示/非表示の指定が出来ます。
どっちの方が良いですかね？あまり数は多くないのでデフォルト表示、見た目が汚くなりそうなら非表示に切り替え……で良いかなと思っているんですが。

**Comment by NAKASHI0131** [comment]
dynmap.marker.signでの解放ですね、了解しました。

レイヤーデフォルト設定はとりあえずは全部表示でいいと思います。
せっかくの新機能ですし。

**Comment by HimaJyun** [comment]
自由枠としてデフォルト非表示の「その他」を用意する事にしました。
