### ISSUE TITLE
TTルールページの調整

### ISSUE THREAD

**Issue by NAKASHI0131** [HimaJyun/amit.jyn.jp#26]
> [ルール](https://amit.jyn.jp/rule/#tt)ページに記載されている注意事項を重要な順番に並び替え

1.建設前に申請する
2.本当に必要か考えてから作る
3.高負荷TTの施設は禁止
4.ためすぎ防止装置を取り付ける
5.TTは公開する
6.位置が分かるようにする
7.デザインに気をつける

> [tt](https://amit.jyn.jp/tt/)に[ルール](https://amit.jyn.jp/rule/#tt)のリンクを記載

最近ルールを読まずTTを建設している人がいたようで、その人曰く見落としていたとのことでした。
実際ルールを読んでいないだろうというお初、住民が多いように感じます。(チャット内で定期的に案内を流すのもあり、、？)

**Comment by HimaJyun** [comment]
優先度高い順に並べるのはアリですね 👍 
最初にページを作った時にBBSから適当に引っ張ってきたのでその辺のことは全く考えてませんでした。🤗

TTページにも記載しておこうと思います。
(個人的にはトラブルさえ起こさないなら勝手にやってどうぞという気持ちではありますが😉)
