### ISSUE TITLE
ぜんそんの村の追加

### ISSUE THREAD

**Issue by NAKASHI0131** [HimaJyun/amit.jyn.jp#27]
[町](https://amit.jyn.jp/town/)ページに[ぜんそんの村](https://amit.jyn.jp/bbs/viewtopic.php?f=15&p=4689#p4689)を追加する

**Comment by HimaJyun** [comment]
c3e6ee8 で軽く調整しました。

**Comment by HimaJyun** [comment]
元ページ: https://amit.jyn.jp/bbs/viewtopic.php?f=15&t=992
