### ISSUE TITLE
画像添付ができない？

### ISSUE THREAD

**Issue by moyashi1119** [HimaJyun/amit.jyn.jp#32]
![スクリーンショット (22)](https://user-images.githubusercontent.com/51190191/104283625-25ed6380-54f4-11eb-8703-2411710be81f.png)
upload files を使っての画像添付ができないようです。
正しい方法ではない場合は正しい方法をお教えいただければ幸いです

**Comment by NAKASHI0131** [comment]
画像貼り付ける場合は自分のフォークしたリポジトリに画像をアップすればそれが適応されるので、、、

自分のリポジトリで試してみてください
