### ISSUE TITLE
町紹介について

### ISSUE THREAD

**Issue by moyashi1119** [HimaJyun/amit.jyn.jp#35]
[町の紹介](https://github.com/HimaJyun/amit.jyn.jp/tree/master/content/town)で[amitサーバー路線図](https://amit.jyn.jp/bbs/viewtopic.php?f=30&t=878)を追加するとアクセス方法が分かりやすいかなと思いました。

ちなみに自分のリポジトリが古いamitのページのままでtownのフォルダが追加されてなかった....
ググったけどちょっと複雑そうなのでとりあえずここで提案しました。

**Comment by NAKASHI0131** [comment]
確かに路線図乗せると便利だと思うんですが、この地図古参ならある程度わかると思うんですが、お初さんが見たら結構混乱しそう、、、
（東京とかの路線図とか初めてだと意味わからん）

[#23](https://github.com/HimaJyun/amit.jyn.jp/issues/23)にもあるとおり、dynmapにマーカーと直線を引ける機能を使って見るのも考えたんですが、ちょっと路線が複雑だな、、、てことで今は放置してるんです、、、

この地図を載せるとなるとdynmapの設定が先かなって思います
（今使ってるのは簡易版なので、路線図を作るとなるとコマンドでごちゃごちゃしなきゃいけない）

**Comment by HimaJyun** [comment]
dynmapに線を引きまくる必要はないけどそのAizennsさんが作ってる地図を画像として載せるのはアリだと思う。

**Comment by moyashi1119** [comment]
路線図の背景をマップにすれば分かりやすそうですね
路線図の元のデータなくしてしまったらしいので作り直しになります
掲載されるのであれば協力者集めるなどして作ろうと思います。

**Comment by HimaJyun** [comment]
作って下さるのであればそれはもちろん喜んで掲載しますね。
(もちろん強制ではないので、めんどくさそうなら無くても良いですが)

Aizennsさんには申し訳ないんですが、添付されてる地図は今のままだと大きすぎるのでどのみち作り直す必要はあると思います。
(試しにフォトショで最適サイズまで縮めてみたんですが、文字がぼやけて見えないので)

僕ならこうする、っていう案ですが
- 横幅を小さく(800pxくらいに)する(将来的な事考えるとInkscapeを使ってSVGとして作る方が良いかも知れない)
- 凡例を省略(デザインが良いので凡例がなくても十分わかる。必要な時だけ出せるようにレイヤーを分けて作り、凡例あり版なし版を容易に作り直せるようにする)
- 凡例レイヤー、線と文字レイヤー、背景レイヤー(位置合わせ用、実際は使わない)を作り、線と文字レイヤーだけを背景透過で出力→プログラムでDynmapの画像データを合成する(地形の変更に追随しやすくする)

みたいにします。
まぁ、「僕ならこうする」というだけの話なので、この辺りは好きに作ってもらって構いません。
Webに載せるなら横幅818pxが最大です、そこだけ気を付けてもらえればこちらとしてはなんでもOK
